{% set name = "oxlint" %}
{% set version = "0.14.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/oxc-project/oxc/archive/oxlint_v{{ version }}.tar.gz
  sha256: a28977286c74350c2f30a04e828c03a58860fb44a7c21cba5d0de8eb0c94ee48

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - cargo-bundle-licenses

test:
  commands:
    - oxlint --help

about:
  home: https://github.com/oxc-project/oxc
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Linter for oxc
  dev_url: https://github.com/oxc-project/oxc

extra:
  recipe-maintainers:
    - danielnachun
