{% set name = "oxlint" %}
{% set version = "0.11.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/oxc-project/oxc/archive/oxlint_v{{ version }}.tar.gz
  sha256: b7ea6d0ea675d0f968a3bb0aa7cf2196fa6b5089edc1068e28aa4991bce64002

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - cargo-bundle-licenses

test:
  commands:
    - oxlint --help

about:
  home: https://github.com/oxc-project/oxc
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Linter for oxc
  dev_url: https://github.com/oxc-project/oxc

extra:
  recipe-maintainers:
    - danielnachun
