context:
  version: "1.69.0"

package:
  name: oxlint
  version: ${{ version }}

source:
  url: https://github.com/oxc-project/oxc/archive/oxlint_v${{ version }}.tar.gz
  sha256: 4efe3e66946a10f5e14abdbf9ebbc48a2be5b27d6b33c671b44c999c6875195a

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses

tests:
  - script:
      - oxlint --help

about:
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Linter for oxc
  homepage: https://github.com/oxc-project/oxc
  repository: https://github.com/oxc-project/oxc

extra:
  recipe-maintainers:
    - danielnachun
    - tdejager
