context:
  oxlint_version: "1.43.0"
  oxfmt_version: "0.28.0"

recipe:
  name: oxc-tools
  # packages have different versions
  # not having a version makes the linter complain
  version: "0"

# This should not be needed, as both packages have build numbers
# but otherwise the linter complains
build:
  number: 0

outputs:
  - package:
      name: oxlint
      version: ${{ oxlint_version }}
    source:
      url: https://github.com/oxc-project/oxc/archive/oxlint_v${{ oxlint_version }}.tar.gz
      sha256: bcf09fda2749b3df123d2a08877dc9b8a7f7e14e8153d5e623e8056378c7986d
    build:
      number: 1
      script:
        - if: unix
          then: build-oxlint.sh
        - if: win
          then: build-oxlint.bat
    requirements:
      build:
        - ${{ compiler('rust') }}
        - ${{ compiler('c') }}
        - ${{ stdlib('c') }}
        - cargo-bundle-licenses
    tests:
      - script:
          - oxlint --help
    about:
      summary: Linter for JavaScript and TypeScript

  - package:
      name: oxfmt
      version: ${{ oxfmt_version }}
    source:
      url: https://github.com/oxc-project/oxc/archive/oxfmt_v${{ oxfmt_version }}.tar.gz
      sha256: d516d3a8ae10cce86345a23001bafbaaad7945f64ebad7b542e3b95bbdadc881
    build:
      number: 0
      script:
        - if: unix
          then: build-oxfmt.sh
        - if: win
          then: build-oxfmt.bat
    requirements:
      build:
        - ${{ compiler('rust') }}
        - ${{ compiler('c') }}
        - ${{ stdlib('c') }}
        - cargo-bundle-licenses
    tests:
      - script:
          - oxfmt --help
    about:
      summary: Formatter for JavaScript and TypeScript

about:
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: JavaScript and TypeScript tooling (oxlint linter and oxfmt formatter)
  homepage: https://github.com/oxc-project/oxc
  repository: https://github.com/oxc-project/oxc

extra:
  recipe-maintainers:
    - danielnachun
    - tdejager
