context:
  version: "1.58.0"

package:
  name: oxlint
  version: ${{ version }}

source:
  url: https://github.com/oxc-project/oxc/archive/oxlint_v${{ version }}.tar.gz
  sha256: 49590614b091d94e90adf316fb8f51a27599fc9c26ad511b1836da6343ef08a8

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses

tests:
  - script:
      - oxlint --help

about:
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Linter for oxc
  homepage: https://github.com/oxc-project/oxc
  repository: https://github.com/oxc-project/oxc

extra:
  recipe-maintainers:
    - danielnachun
    - tdejager
