outputs:
  - package:
      name: oxlint
      version: "1.43.0"
    source:
      url: https://github.com/oxc-project/oxc/archive/oxlint_v${{ version }}.tar.gz
      sha256: bcf09fda2749b3df123d2a08877dc9b8a7f7e14e8153d5e623e8056378c7986d
    build:
      number: 0
      script:
        - ${{ "build-oxlint.sh" if unix }}
        - ${{ "build-oxlint.bat" if win }}
    requirements:
      build:
        - ${{ compiler('rust') }}
        - ${{ compiler('c') }}
        - ${{ stdlib('c') }}
        - cargo-bundle-licenses
    tests:
      - script:
          - oxlint --help
    about:
      license: MIT
      license_file:
        - LICENSE
        - THIRDPARTY.yml
      summary: Linter for JavaScript and TypeScript
      homepage: https://github.com/oxc-project/oxc
      repository: https://github.com/oxc-project/oxc

  - package:
      name: oxfmt
      version: "0.28.0"
    source:
      url: https://github.com/oxc-project/oxc/archive/oxfmt_v${{ version }}.tar.gz
      sha256: d516d3a8ae10cce86345a23001bafbaaad7945f64ebad7b542e3b95bbdadc881
    build:
      number: 0
      script:
        - ${{ "build-oxfmt.sh" if unix }}
        - ${{ "build-oxfmt.bat" if win }}
    requirements:
      build:
        - ${{ compiler('rust') }}
        - ${{ compiler('c') }}
        - ${{ stdlib('c') }}
        - cargo-bundle-licenses
    tests:
      - script:
          - oxfmt --help
    about:
      license: MIT
      license_file:
        - LICENSE
        - THIRDPARTY.yml
      summary: Formatter for JavaScript and TypeScript
      homepage: https://github.com/oxc-project/oxc
      repository: https://github.com/oxc-project/oxc

extra:
  recipe-maintainers:
    - danielnachun
