context:
  version: "1.81.0"

package:
  name: oxlint
  version: ${{ version }}

source:
  url: https://github.com/oxc-project/oxc/archive/oxlint_v${{ version }}.tar.gz
  sha256: 29431517f760ca4c6ba58d4416faf306bc9fceb0e11f9889a85b674b1ea34d60

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses

tests:
  - script:
      - oxlint --help

about:
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Linter for oxc
  homepage: https://github.com/oxc-project/oxc
  repository: https://github.com/oxc-project/oxc

extra:
  recipe-maintainers:
    - danielnachun
    - tdejager
